### PR TITLE
Draggable autohide tab

### PR DESCRIPTION
**Pull request by SyarifFakhri**
rearrange_tabs

Hi @githubuser0xFFFF , hope you are doing well :). This is a tiny QOL feature to allow rearranging of auto hide tabs via dragging.

All of the functional changes are in [Add draggable auto hide tab functionality](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/commit/a48108e4493f62b454bcd7619652c97dc5e8d2a1) and [fix flicker](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/commit/e949dcd9b69a15b22bf01a96c0ecefbf1fbc48e8), the rest of the commits are only formatting or merge changes. 

Some details:

1. The implementation of the dragging is similar to the DockWidgetTab implementation, however I added live update while dragging, so it reacts on mouse move, and finalizes the movement on mouse release instead. I believe this is more intuitive for the user and gives a nice live update while dragging.
2. I changed the open from mouse press to mouse release, so that a user can drag without opening the auto hide tab.

Please test and let me know if there any changes you'd like me to make, thanks!

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Hi @SyarifFakhri, thank you for your pull request.

What I wondering is, do users realy sort their tabs? Do you think, that users spend the time, to drag their tabs around? I work with ADS since years and I have never sorted the tabs of a tabbed dock area and I have never seen some other users here in our company that does this. So I'm not sure, if this is realy a feature that someone uses. Yes, it is cool but I'm not sure, if we should add this.

Regarding the AutoHide feature, there are some cool features, that would be more interesting for me:

- the option to drag a auto hide tab to a new location or into a floating widget like it is possible with the tabs of a dock area
- the option to AutoHide a dock widget, by dragging it to the borders of a dock container - that means, if a dragged dock widget comes close to the border, a special AutoHide overlay is shown, and if the user releases the mouse button the dock widget will be added to the AutoHide sidebar

When I use the AutoHide feature, I often asked myself, why I need to unpin an AutoHide widget, before I can drag it to a new location or to a different AutoHide sidebar.

**Comment by SyarifFakhri** [comment]
> What I wondering is, do users realy sort their tabs? Do you think, that users spend the time, to drag their tabs around? I work with ADS since years and I have never sorted the tabs of a tabbed dock area and I have never seen some other users here in our company that does this. So I'm not sure, if this is realy a feature that someone uses. Yes, it is cool but I'm not sure, if we should add this.

I think it depends on the application, when the number of tabs are very high I think it really does come in handy, as otherwise the tabs you want to access often can be quite far apart from each other. It's also useful if new tabs are being created often (like in an editor type application).  Personally I do rearrange tabs quite a bit.

> Regarding the AutoHide feature, there are some cool features, that would be more interesting for me:
> - the option to drag a auto hide tab to a new location or into a floating widget like it is possible with the tabs of a dock area
> - the option to AutoHide a dock widget, by dragging it to the borders of a dock container - that means, if a dragged dock widget comes close to the border, a special AutoHide overlay is shown, and if the user releases the mouse button the dock widget will be added to the AutoHide sidebar

Couldn't agree with you more. I actually wanted to implement these features but ran out of time (and the PR was really getting too big as it is haha!). I would love to implement these features if possible, and I see rearranging auto hide tabs as a stepping stone feature to these features you listed. Ideally a user should be able to rearrange, drag it out and drag it back in seamlessly, basically matching the features that exist with the current dock tabs :)

**Comment by githubuser0xFFFF** [comment]
@SyarifFakhri I will close this pull request for the moment, because I will not merge it in the near future.

**Comment by githubuser0xFFFF** [comment]
I close the pull request because the same functionality is now possible via Auto-Hide drag & drop functionality

**Pull request closed without merging**
