### PR TITLE
Fix issue with windeployqt

### PR DESCRIPTION
**Pull request by nolankramer**
See issue https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/682

This fixes the deployment issues with `windeployqt`.

# Before

```
$> cd build\x64\bin\Debug
$> windeployqt --dry-run --list mapping .\SimpleExample.exe
Unable to find dependent libraries of C:\Qt\6.6.3\msvc2019_64\bin\qt6advanceddockingd.dll :Cannot open 'C:/Qt/6.6.3/msvc2019_64/bin/qt6advanceddockingd.dll': The system cannot find the file specified.
```

# After

```
$> cd build\x64\bin\Debug
$> windeployqt --dry-run --list mapping .\SimpleExample.exe
Adding in plugin type generic for module: Qt6Gui
Adding in plugin type iconengines for module: Qt6Gui
Adding in plugin type imageformats for module: Qt6Gui
Adding in plugin type networkinformation for module: Qt6Network
Adding in plugin type platforminputcontexts for module: Qt6Gui
Adding in plugin type platforms for module: Qt6Gui
Adding in plugin type styles for module: Qt6Widgets
Adding in plugin type tls for module: Qt6Network
Warning: Cannot find Visual Studio installation directory, VCINSTALLDIR is not set.
"C:\Qt\6.6.3\msvc2019_64\bin\Qt6Cored.dll" "Qt6Cored.dll"
"C:\Qt\6.6.3\msvc2019_64\bin\Qt6Guid.dll" "Qt6Guid.dll"
"C:\Qt\6.6.3\msvc2019_64\bin\Qt6Networkd.dll" "Qt6Networkd.dll"
"C:\Qt\6.6.3\msvc2019_64\bin\Qt6Svgd.dll" "Qt6Svgd.dll"
"C:\Qt\6.6.3\msvc2019_64\bin\Qt6Widgetsd.dll" "Qt6Widgetsd.dll"
"C:\Qt\6.6.3\msvc2019_64\bin\opengl32sw.dll" "opengl32sw.dll"
"C:\Qt\6.6.3\msvc2019_64\bin\D3Dcompiler_47.dll" "D3Dcompiler_47.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\generic\qtuiotouchplugind.dll" "generic\qtuiotouchplugind.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\iconengines\qsvgicond.dll" "iconengines\qsvgicond.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\imageformats\qgifd.dll" "imageformats\qgifd.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\imageformats\qicod.dll" "imageformats\qicod.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\imageformats\qjpegd.dll" "imageformats\qjpegd.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\imageformats\qsvgd.dll" "imageformats\qsvgd.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\networkinformation\qnetworklistmanagerd.dll" "networkinformation\qnetworklistmanagerd.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\platforms\qwindowsd.dll" "platforms\qwindowsd.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\styles\qwindowsvistastyled.dll" "styles\qwindowsvistastyled.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\tls\qcertonlybackendd.dll" "tls\qcertonlybackendd.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\tls\qopensslbackendd.dll" "tls\qopensslbackendd.dll"
"C:\Qt\6.6.3\msvc2019_64\plugins\tls\qschannelbackendd.dll" "tls\qschannelbackendd.dll"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_ar.qm" "translations\qt_ar.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_ar.qm" "translations\qtbase_ar.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_bg.qm" "translations\qt_bg.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_bg.qm" "translations\qtbase_bg.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_ca.qm" "translations\qt_ca.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_ca.qm" "translations\qtbase_ca.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_cs.qm" "translations\qt_cs.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_cs.qm" "translations\qtbase_cs.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_da.qm" "translations\qt_da.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_da.qm" "translations\qtbase_da.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_de.qm" "translations\qt_de.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_de.qm" "translations\qtbase_de.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_en.qm" "translations\qt_en.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_en.qm" "translations\qtbase_en.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_es.qm" "translations\qt_es.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_es.qm" "translations\qtbase_es.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_fa.qm" "translations\qt_fa.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_fa.qm" "translations\qtbase_fa.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_fi.qm" "translations\qt_fi.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_fi.qm" "translations\qtbase_fi.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_fr.qm" "translations\qt_fr.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_fr.qm" "translations\qtbase_fr.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_gd.qm" "translations\qt_gd.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_gd.qm" "translations\qtbase_gd.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_he.qm" "translations\qt_he.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_he.qm" "translations\qtbase_he.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_hr.qm" "translations\qt_hr.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_hr.qm" "translations\qtbase_hr.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_hu.qm" "translations\qt_hu.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_hu.qm" "translations\qtbase_hu.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_it.qm" "translations\qt_it.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_it.qm" "translations\qtbase_it.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_ja.qm" "translations\qt_ja.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_ja.qm" "translations\qtbase_ja.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_ko.qm" "translations\qt_ko.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_ko.qm" "translations\qtbase_ko.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_lv.qm" "translations\qt_lv.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_lv.qm" "translations\qtbase_lv.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_nl.qm" "translations\qt_nl.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_nl.qm" "translations\qtbase_nl.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_nn.qm" "translations\qt_nn.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_nn.qm" "translations\qtbase_nn.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_pl.qm" "translations\qt_pl.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_pl.qm" "translations\qtbase_pl.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_pt_BR.qm" "translations\qt_pt_BR.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_pt_BR.qm" "translations\qtbase_pt_BR.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_ru.qm" "translations\qt_ru.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_ru.qm" "translations\qtbase_ru.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_sk.qm" "translations\qt_sk.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_sk.qm" "translations\qtbase_sk.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_tr.qm" "translations\qt_tr.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_tr.qm" "translations\qtbase_tr.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_uk.qm" "translations\qt_uk.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_uk.qm" "translations\qtbase_uk.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_zh_CN.qm" "translations\qt_zh_CN.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_zh_CN.qm" "translations\qtbase_zh_CN.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qt_zh_TW.qm" "translations\qt_zh_TW.qm"
"C:\Qt\6.6.3\msvc2019_64\translations\qtbase_zh_TW.qm" "translations\qtbase_zh_TW.qm"
```

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Thank you for the pull request. I understand your problem or the idea behind the pull request. But the change of the library name was introduced explicitely by another pull request #489. So you change will "revert" this pull request. I will ask the author of the #489 pull request to comment this pull request.

**Comment by nolankramer** [comment]
I'm happy to choose another name format in this fix, it can even have the version number of qt somewhere in it, but the prefix MUST NOT be "qt{VERSION}". A few good examples could be:
"q{VERSION}advanceddocking"
or
"qtadvanceddocking{VERSION}"

**Comment by githubuser0xFFFF** [comment]
@nolankramer Ok, this sounds reasonable for me. Then please go with:

qtadvanceddocking-qt6
qtadvanceddocking-qt5

This clearly indicates, that the 5 and 6 are not the version number of the qtadvanceddocking library but of the qt version.

**Comment by nolankramer** [comment]
@githubuser0xFFFF Agreed, and done. Thanks for the speedy reply.

I've pushed the change here and it is ready for review.

**Comment by bebuch** [comment]
Please note such breaking changes in the Release Notes. Any CMake code that uses the library must be changed do to this PR. It becomes not better if you don't even know whats going on.

**Pull request merged**
