### PR TITLE
ADS Translation, Suffix for "loadPerspectives/savePerspectives"

### PR DESCRIPTION
**Pull request by ix07**
- Added QTranslator to provide translations of ADS texts (context menus etc.)
- Added German translations
- Added "Suffix" to "loadPerspectives/savePerspectives" to enable saving of multiple perspectives into one settings object

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Thank you for this pull request. Could you please create a seperate pull request for the two different features?

Pull request 1: QTranslator
Pull request 2: loadPerspectives/savePerspectives with suffix.

Could you please elaborate about the intention of the loadPerspectives/savePerspectives change? What is the use case for this?

**Comment by ix07** [comment]
> Could you please elaborate about the intention of the loadPerspectives/savePerspectives change? What is the use case for this?

Consider a software with multiple dock managers  - if you want to use "loadPerspectives"  "savePerspectives" you would now have to use different "QSettings" objects to store/retrieve perspectives. With the proposed change (which would not break existing code because it has an empty default value) you could now use one QSettings-object to persist perspectives into one file/registry.

QSettings settings;
ads::CDockManager* dm1 = new ads::CDockManager;
ads::CDockManager* dm2 = new ads::CDockManager;
dm1->savePerspectives(settings, "dm1");
dm2->savePerspectives(settings, "dm2");

**Comment by githubuser0xFFFF** [comment]
Is it possible to use multiple dock managers with the current source code without any modifications?

**Comment by ix07** [comment]
Yes. We do that in two of our applications.

In one of our applications we even have a nested system. There is an "outer" dock manager, and in the central area of that "outer" manager, there is a completely separate "inner" dock manager which display documents in a grid/free layout. You cannot move docks between those managers, but that's totally acceptable for us.

**Comment by ix07** [comment]
>  Could you please create a seperate pull request for the two different features?

Of course - but I have never done that before (this is my first pull request on GitHub). I will have to find out how first. Will try do it ASAP.

**Comment by githubuser0xFFFF** [comment]
For the first pull request you create a branch from master and add only the changes for the translation. The you create a pull request from this branch. Then you create another branch from master and implement the perspective saving relevant changes. Then you create the second pull request from this second branch,

**Comment by ix07** [comment]
Thanks. I had to do it in my fork though, because I can't add branches to this repository (rights). I created two separate pull requests bases on those two branches. I think we can close this.

**Pull request closed without merging**
