### PR TITLE
add maximize button to FloatingWidgetTitleBar

### PR DESCRIPTION
**Pull request by helywin**
Add maximize button and mouseDoubleClickEvent function to implement maximize as in Windows

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Thank you for you pull request. I will review it within the next days.

**Comment by helywin** [comment]
Thanks for your advice, I'll fix it

**Comment by SleepProgger** [comment]
So, did this PR die ?
It's a feature i, and probably a lot of other people, would love to have.

**Comment by githubuser0xFFFF** [comment]
You can checkout the code of the pull request and play around with it.

**Pull request closed without merging**
