### PR TITLE
FIX: Update Python bindings for 3.4.2 and current master.

### LINKED ISSUE #191: PyQt bindings doesn't work correctly.
```
/usr/bin/python3.8 test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from PyQtAds.QtAds import *
  File "/usr/lib/python3.8/site-packages/PyQtAds-3.4.2-py3.8-linux-x86_64.egg/PyQtAds/QtAds/__init__.py", line 1, in <module>
    from .ads import ads
ImportError: /usr/lib/python3.8/site-packages/PyQtAds-3.4.2-py3.8-linux-x86_64.egg/PyQtAds/QtAds/ads.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTVN3ads15CTitleBarButtonE

Process finished with exit code 1
```

test.py:

```
import sys

from PyQt5 import QtWidgets, QtGui, QtCore
from PyQtAds.QtAds import *


class UI_MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None, flags=None):
        super(UI_MainWindow, self).__init__(parent=parent, flags=None)
        central = DockManager()
        self.setCentralWidget(central)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = UI_MainWindow()
    window.show()
    app._exec()
```

### PR DESCRIPTION
**Pull request by hhslepicka**
Thank you, @n-elie for the help with the Windows fix.

Closes #191

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Thank you very much

**Comment by githubuser0xFFFF** [comment]
@hhslepicka I just added a Python section to the main README.ms file. Feel free to create a pull request if you would like to change something or if you would like to add some additional information or install instructions

**Comment by n-elie** [comment]
@githubuser0xFFFF Is there a way that we could get notified when you make a change to the headers so we can update the sip files?
It would help having working bindings when you publish a new release

**Comment by hhslepicka** [comment]
@githubuser0xFFFF thank you. Please also add @klauer which did a lot of work on the bindings as well. 

I am monitoring the repository but it is difficult since GitHub only tells me about issues and Pull Requests.

@githubuser0xFFFF would you be willing to use Pull Requests even for your own changes? I am not telling you to wait for review or anything but it would allow us to get notifications, check the changes and submit the proper PR to fix the bindings.

For now we are acting to remedy the fact once a new release is done and we apply a patch at the conda-forge recipe.

**Comment by githubuser0xFFFF** [comment]
@n-elie So that means, every change in a header requires an update of the Python bindings?

I would propose, that I create an issue like "Update Python Bindings" and as soon as I modify the headers I reopen the issue. Would thi trigger a notification?

**Comment by hhslepicka** [comment]
That would work... we get notifications for new issues.

**Comment by githubuser0xFFFF** [comment]
Also if I reopen it?

**Comment by hhslepicka** [comment]
Usually if we set the `Watch` to `Watching` we get notified for every conversation at the repository... I get messages for reopened issues as well.

**Comment by githubuser0xFFFF** [comment]
I just created the the issue #197 Update Python Bindings - please watch the issue te get informed if an update of the Python bindings is required.

I just pushed the new focus highlighting feature that requires an update of the Python bindings.

**Comment by githubuser0xFFFF** [comment]
@githubuser0xFFFF 

> @githubuser0xFFFF thank you. Please also add @klauer which did a lot of work on the bindings as well.

Yes, I will do this, but this is the reason I asked for a pull request - this way you can change the Python section the way you want.

**Pull request merged**
