### PR TITLE
setConfigFlag(CDockManager::DockAreaHasCloseButton, false) is not properly handled

### PR DESCRIPTION
**Pull request by mvidelgauz**
Buttons are still created in DockAreaTitleBarPrivate::createButtons(), they appear on the screen behind the main app window, each one indicated on the taskbar. They are also left on the screen when the main app exits and the user needs to close each of them one by one.

WidgetCreated

WidgetsLeft

WidgetsOnTaskBar

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Hi,

thank you for your contribution. From reading your code I would expect that your pull request does a litle bit more than only fixing `setConfigFlag(CDockManager::DockAreaHasCloseButton, false)`?

**Comment by mvidelgauz** [comment]
Hi, 
sorry, but yes my repo's master branch already contains another mod (I mentioned it in the issue I added). I am new to GittHub and only yesterday I learned that I am supposed to implement each feature on a separate branch...
But the pull request was created after I pushed only this fix and before I pushed other things. Are you saying it is affected by my following commits?
If yes could you please give me a tip of how I can create isolated pull requests in my repo?

**Comment by mvidelgauz** [comment]
And yes the same problem exists also for DockAreaHasUndockButton and DockAreaHasTabsMenuButton flags, my first mod addressed them also -  in the same way as for DockAreaHasCloseButton

**Comment by mvidelgauz** [comment]
And there was a conflict between my mod and your latest commit.
I resolved it and merged into my master... Should I now re-create pull requests?

**Comment by githubuser0xFFFF** [comment]
I'm not a git expert, but for me it is always easier to integrate small pull requests because they are easier to understand and to test. So for your contribution, the best for me would be 3 pull requests:

1. Pull request: fix the broken DockAreaHasCloseButton issue
2. Pull request: add the other configuration flags (DockAreaHastabsMenu)
3. Pull request: add the feature with the allowed areas

Because I just merged a different pull request, there is now a conflict with your pull request. You can move all your changes into a feature branch - just create a new branch from you local master.

Then pull all the changes from my master and reset your master to the same state like my master. that means you have the same master like me and a feature branch with all the new features. Then you could add the changes for the first pull request from your feature branch to the master or a different integration branch. An then you can create a pull request. If the pull request is integrated you could create the next pull request.

Is this possible for you  - it would help me a lot to integrate your changes.

Thank you.

**Comment by mvidelgauz** [comment]
Ok, I am working now on resetting my master to yours and creating dedicated branches for my changes. Let's close this pull requests for now?

**Comment by mvidelgauz** [comment]
Closing this pull request as the isolated fix is issued as another request #105

**Pull request closed without merging**
