### PR TITLE
Add PyQt5 bindings

### PR DESCRIPTION
**Pull request by n-elie**
Hello,

Thanks for this great project. I wanted to use it from Python so I started writing sip files to create a PyQt5 compatible package.

It is surely not perfect but there is at least two working examples borrowed from the pure Python port [qtpydocking](https://github.com/klauer/qtpydocking)

There is a setup.py that can be used to build: `python setup.py build`
And a conda recipe: `conda build recipes`

Packaging could certainly be improved.
I would be very happy to hear from you about this.

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Hello,

thank you for your pull request. I cannot test it yet but because it does not break the build, I will merge it.

Thank you, :o)

**Comment by githubuser0xFFFF** [comment]
Hi,

the PyQt bindings are not up to date anymore. A user just reported an issue #124. Would you like to update the Python bindings or should I remove Python support?

**Comment by hhslepicka** [comment]
Hi,

Please don’t remove it. I can help with keeping it up to date

**Comment by n-elie** [comment]
Working on it

**Pull request merged**
