### PR TITLE
FIX: Add Q_OS_MACOS flag to moc compiler.

### PR DESCRIPTION
**Pull request by hhslepicka**
Continuing the work from PR #126

### CODE REVIEW

**Comment by hhslepicka** [comment]
@githubuser0xFFFF this PR will receive more fixes for the SIP and Python bindings as @n-elie mentioned before. 
Do you mind to hold on into the release until we get it all in?
Thanks and sorry for the confusion.

**Comment by githubuser0xFFFF** [comment]
I'm not in a hurry

**Comment by hhslepicka** [comment]
@n-elie do you mind to give it a look?

**Comment by n-elie** [comment]
What do you think of using this kind of code in `FloatingDockContainer.sip`:
```%ModuleHeaderCode
#include <FloatingDockContainer.h>
%End

%If (Linux)
    class tFloatingWidgetBase : QDockWidget
    {};
%End

%If (!Linux)
    class tFloatingWidgetBase : QWidget
    {};
%End

namespace ads
{

class IFloatingWidget;


class CFloatingDockContainer : tFloatingWidgetBase, ads::IFloatingWidget
{
    
    %TypeHeaderCode
    #include <FloatingDockContainer.h>
    %End

...

}```

This would prevent having to maintain two different branches of the same file just because of the different superclasses. It compiles and don't crash but this may not be not superclean.

**Comment by n-elie** [comment]
Found a better way to do it using a typedef:

```C++
typedef QWidget tFloatingWidgetBase;
%If (WS_X11)
    typedef QDockWidget tFloatingWidgetBase;
%End
```
Also the platforms checks are wrong. We should use `WS_X11` instead of `Linux` as defined in `QtCoreMod.sip`:
```
%Platforms {WS_X11 WS_WIN WS_MACX}
```
This is the tags passed by sip by default. Without this change, `issubclass(QtAds.CFloatingDockContainer, QDockWidget)` return `False` instead of `True` and the `CFloatingWidgetTitleBar` class is not available from the Python world.

**Comment by hhslepicka** [comment]
@n-elie please feel free to push changes to my branch and I will test them.

**Comment by hhslepicka** [comment]
I am applying the suggested changes now and I will push it after testing it here.

**Comment by hhslepicka** [comment]
@n-elie it is now good for a new review.

**Comment by n-elie** [comment]
Thanks for updating the PR. Not a git expert here, so I submitted a PR to your branch. Wasn't it the right thing to do?

**Comment by hhslepicka** [comment]
@n-elie sorry, I completely missed it... I will cherry-pick some of the changes since there is a problem with the way you wrapped the type in here: https://github.com/hhslepicka/Qt-Advanced-Docking-System/pull/1/commits/17b63563ba1770627c1f5919672de5ad9ee86e67#diff-e6aacfae87c77f5a2b6567637f526a68R8

**Comment by hhslepicka** [comment]
@n-elie I cherry-picked your changes. Please let me know if I missed something.

**Comment by n-elie** [comment]
@hhslepicka Ok, seems good for me

**Comment by hhslepicka** [comment]
@n-elie awesome, thank you for reviewing it and for all the help.
@githubuser0xFFFF this one is ready to go.

**Comment by githubuser0xFFFF** [comment]
Thank you guys for this big contribution. I just merged it.

**Comment by githubuser0xFFFF** [comment]
If someone would like to add a small section about the Python integration (features, installation via condaforge or pip and so on) feel free to create a pull request.

**Pull request merged**
