### PR TITLE
FIX: Update Python SIP bindings 3.2.1 & Linux Crash

### LINKED ISSUE #124: Segfault when undocking - Linux
Hi,

When using the package with a RHEL linux system I am experiencing a segmentation fault when the detach button is pressed or when the screen is dragged.
I am trying to investigate the issue but I decided to open the issue here in case someone is able to shine some light into it.

Here is part of the backtrace:
```
#0  0x00007f70a3448edc in QWidget::isWindow() const () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#1  0x00007f70a34f7817 in QDockWidgetLayout::minimumSize() const () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#2  0x00007f70a3456024 in QLayout::totalMinimumSize() const () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#3  0x00007f70a3456c30 in QLayout::activate() () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#4  0x00007f70a346d8fe in QWidgetPrivate::setVisible(bool) () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#5  0x00007f707c793b84 in ads::CDockAreaTabBar::makeAreaFloating(QPoint const&, ads::eDragState) ()
   from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQtAds-2.7.0-py3.6-linux-x86_64.egg/PyQtAds/QtAds/ads.cpython-36m-x86_64-linux-gnu.so
#6  0x00007f707c7979be in ads::CDockAreaTitleBar::onUndockButtonClicked() () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQtAds-2.7.0-py3.6-linux-x86_64.egg/PyQtAds/QtAds/ads.cpython-36m-x86_64-linux-gnu.so
#7  0x00007f70a62657b8 in QMetaObject::activate(QObject*, int, int, void**) () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Core.so.5
#8  0x00007f70a34db1fe in QAbstractButton::clicked(bool) () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#9  0x00007f70a34db8b7 in ?? () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#10 0x00007f70a34dc14c in ?? () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#11 0x00007f70a34dc1e8 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
```

QtAds version is 3.0.0.

### PR DESCRIPTION
**Pull request by hhslepicka**
Closes #124 

Part of the fixes here were based on work by @n-elie the other fixes were by @klauer.

The main issue with the crash was that the base classes at SIP were wrong for Linux resulting in undefined behavior and crash.

Tested locally with Linux (RHEL7) and macOS.

### CODE REVIEW

**Comment by hhslepicka** [comment]
@githubuser0xFFFF can we get this merged and a new release?

**Comment by n-elie** [comment]
Great job!
I think there is a few things to fix though:

- IIRC there is a test for Q_OS_MACOS somewhere so we need to add this case in the `get_moc_args` func.

- `meta.yaml` needs to be update because `LICENSE` file has been renamed to `LICENSE.md`

- I updated `demo.py` to match the recent changes and created a `example.py` file to match the examples in C++. You can find them [here](https://github.com/metgem/Qt-Advanced-Docking-System/commit/4a77d857da88748436e03690c371bafd69c5f9b8#diff-c8d39403e47b66a2083b52686280f1e3) and [here](https://github.com/metgem/Qt-Advanced-Docking-System/commit/4a77d857da88748436e03690c371bafd69c5f9b8#diff-361124b383dbcfcd37bb8bdf94243df4)

**Comment by hhslepicka** [comment]
@n-elie I will pick your `demo.py` and also `example.py` files and also address the other comments that you raised.
FYI, I added this package at `conda-forge` (https://github.com/conda-forge/pyqtads-feedstock) a while ago so people can just `conda install -c conda-forge pyqtads`.
Please let me know if you would like to be added as a maintainer there as well.

**Comment by githubuser0xFFFF** [comment]
Thank you very much for your help keeping the Python stuff working - just merged your pull request

**Comment by n-elie** [comment]
@hhslepicka I was not aware of the conda-forge package. This is great! The recipe in this repo is not needed anymore then. And yes, I could help maintaining the package.

**Pull request merged**
