### PR TITLE
a few bugs

### PR DESCRIPTION
**Pull request by 7c0o**
Sometimes the synchronous calculation of the rectangular area fails

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Thank you for this pull request. I cannot reproduce the problem here, so maybe it is related to your application. Can you post a video that I can understand the intention of this pull request?

**Comment by 7c0o** [comment]
> Thank you for this pull request. I cannot reproduce the problem here, so maybe it is related to your application. Can you post a video that I can understand the intention of this pull request?

You should add many tab widgets.
This problem is reproduced when the length of the tab bar exceeds the length of the QSrcollArea's viewport

**Comment by githubuser0xFFFF** [comment]
Should I test this under Windows or Linux or is it reproducible on both systems?

**Comment by 7c0o** [comment]
> Should I test this under Windows or Linux or is it reproducible on both systems?

windows

**Comment by 7c0o** [comment]
> Please describe the exact steps I need to do to reproduce the problem that you try to solve with this change:
> 
> ```c++
> 		QTimer::singleShot(0, [&, TabWidget]{
> 			    _this->ensureWidgetVisible(TabWidget);
> 			});
> ```
> 
> If I cannot reproduce the problem here, I will not merge this change - sorry.

**Before modification**
image
image
**After modification**
image

**Comment by githubuser0xFFFF** [comment]
Thank you for your bug fixes. I was able to reproduce the problem here and merged your changes.

**Comment by sarimisar** [comment]
This fix seems to have introduced a regression when _this is deleted before the lambda slot occurred, for example deleting the DockManager (and consequently _this) immediately after the execution of updateTabs function (we encountered this problem in our software). A safer solution can be the following:

```
QTimer::singleShot(0, _this, [&, TabWidget]{
   _this->ensureWidgetVisible(TabWidget);
});
```

**Pull request merged**
