### PR TITLE
Add option to have dock not closable when isAutoHide and add minimize button to auto hide dock

### PR DESCRIPTION
**Pull request by tttttthia**
Hi @githubuser0xFFFF :)

This is a pull request to:
- Add flag to configure whether an auto hide dock can close (when in auto hide mode)
- Add flag to include a minimize button to hide the auto hide dock.

The reason for these are because some users are used to clicking `X` to "hide" a dock instead of clicking outside the dock to hide it - so they would expect the dock to be hidden instead of closed. Hence, an option to have a minimize button to the auto hide dock that hides the dock and also an option to disable closing the auto hide dock.

### CODE REVIEW

**Comment by tttttthia** [comment]
> Have you checked this configuration flag: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/doc/user-guide.md#autohideclosebuttoncollapsesdock

Yes, this flag `AutoHideCloseButtonCollapsesDock` is a global config flag and we are looking for something that is configurable for individual dock widgets - so that some are closable when auto hide and some are not. And it would be clearer to have two buttons that convey minimize(collapse) vs close.

**Comment by githubuser0xFFFF** [comment]
Why do you need the flag `AutoHideDockWidgetClosable` because there is already the flag `DockWidgetClosable`? If I can close a dock widget that has the flag `AutoHideDockWidgetClosable` set but not the flag `DockWidgetClosable`, then it would mean that  `AutoHideDockWidgetClosable` overrides `DockWidgetClosable`. That means, a user can simply pin a DockWidget to close it if `DockWidgetClosable` is not set.

**Comment by tttttthia** [comment]
My intention is to disable close button for docks when auto hide (pinned). As long as `DockWidgetClosable` is set, user would still be able to close the dock by right click context menu or Unpin (Dock) then close. 

I've changed the name of the flag to `DisableCloseButtonWhenAutoHide` to make it easier to understand.

**Comment by githubuser0xFFFF** [comment]
Ok, I understand. But why do you want do disable the close button? If you say, that the user can still close the the dock with the context menu and if you have an explicit minimize button, why do you want to disable the close button. Do you think the user will accidentally click the close button instead of your new minimize button?

**Comment by tttttthia** [comment]
That's right - many of our customers are accidentally pressing the Close button when they actually have the intention to ***hide*** the auto-hide dock. Adding the minimize button helps them hide the dock. But from habit, user tend to go for the top right close button, so we want to prevent that from happening when these docks are already in auto hide mode (which means user probably do not want to actually close them).

**Comment by githubuser0xFFFF** [comment]
So in this case the existing flag AutoHideCloseButtonCollapsesDock would be the perfect match - the user hides the auto hide container instead of closing it accidentally without presenting a non working close button ?

**Comment by githubuser0xFFFF** [comment]
@tttttthia I just pushed a commit that should meet your requirements. I added a minimize action to the Auto Hide title bar context menu:

grafik

That means, the action of the close button depends on the autohide flag `CDockManager::AutoHideCloseButtonCollapsesDock`. I adjusted the tooltip of the close button to show "Minimiz" in case the flag is enabled.

The context menu action do exactly, what the name indicates:

- **Close** - closes the auto hide widget
- **Minimize** - minimizes the auto hide widget

I think. with this change, your pull request is obsolete and I ask you, if I can close it.

**Comment by tttttthia** [comment]
Your commit with the option to minimize sounds like it could solve some of our issues. However, in our case, we need **certain** auto-hide docks to be **both** closable and also minimizable (Both minimize button and close button enabled). The `DisableCloseButtonWhenAutoHide` flag is set per dock (under `DockWidgetFeature`) - some docks to be closable when auto hide and some not.

**Comment by githubuser0xFFFF** [comment]
@tttttthia If you would like to get something merged into an open source project, then you need to convince the maintainers or here the mainteiner, that there are good uses cases for this change, why you need this change, what the change improves and why maybe other users also benefit from this change.

Sorry, but the statement:

> However, in our case, we need certain auto-hide docks to be both closable and also minimizable (Both minimize button and close button enabled). 

does not convince me. It is no explanation why do you need this change an what are you trying to solve. All Auto Hide docks are now closable and minimizable.

**Comment by tttttthia** [comment]
Okay I understand your point of view. We will rethink how to solve our use case and make do with your new changes for now. You can close this. Thank you for your time.

**Pull request closed without merging**
