### PR TITLE
Widgets menu construction

### PR DESCRIPTION
**Pull request by mvidelgauz**
NOT YET READY, I just would like you to review the concept here:

Mainly change of `CDockAreaTitleBar::onTabsMenuAboutToShow()` - I think that menu for switching between DockWidgets should not depend on tabs visibility (and even existence). Also, I think that menu items should use DockWidget's names, icons, and tooltips.  IMO TabWidget is there to reflect those DockWidget's properties, but not to own them.

(in fact, it seems to me that "WidgetsMenu" could be a better name for it than "TabsMenu" because the user uses it to select visible widget, tabs are only helpers...)

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
I understand your idea, but I'm not completely with you - at least not enough to do this change just for the change.

For me, the tabs menu button belongs to the tabs. I could imagine, to create a tabbar component, that is not in any way related to docking and that has exactly the same features. The tab menu is required to navigate the tabs, if the tab text is elided. So for me it is more related to the tabs, then to the dock widgets.

If the toolTip() belongs to the DockWidget or to the tab is another question. I decided to put it into the tab, because it is only shown in the tabs and in the tabs menu - which in turn is related to the tabs and not to the dock widget.

So at the moment I'm not completely convinced to to this change.

**Comment by mvidelgauz** [comment]
To be honest, I expected this change not to be easily accepted, but I will appreciate it if you allow me to try...

_"For me, the tabs menu button belongs to the tabs"_ this is the key point which we see a bit differently. For me, as a user, that menu is _a tool for switching between widgets, not tabs_. In other words, this menu is _View and Controller_ for the _Model_ which consists of a list of available widgets. And the _TabBar_ is just another _View and Controller_ for the same model. IMO, a _View-Controller_ should connect directly to its Model, maybe a delegate (filter, etc.), but not to another View-Controller.

I got the impression that you have a concept where tabs and widgets are strictly bound. And probably this concept perfectly fits the paradigm of your application. But following idea from another PR, ADS may evolve to the point where users can derive from TitleBar, reimplement it's looks and feel - but only partially, and still use that menu for widget switching. I recall apps that use radio buttons or even push buttons on the bar to switch between active contents. Yes, it sounds ugly at first, but it fits certain other application concepts. (imitation of vintage TV receivers is just one example)

Showing that menu only when tab labels are elided is our very recent enhancement. I can imagine an app that doesn't want tabs at all and only use that menu, which is always visible. (Again, not for your application but for some other)

And one more point. Today, you already expose non-const access to the tab, which allows user to just hide the tab (try to activate that `TestHiddenTabs` in mainwindow.cpp in my branch). I am not sure if this is made by design or it is a design bug (namely violation of "Open–closed principle") but it is there. The user can (ab)use it for whatever reason and then the menu will pop up with an empty line... (I know that after re-arranging widgets between areas hidden tab will be visible again, which makes me consider this non-const access as a bug - if you gave it on purpose you should account for a possibility of user calling `setVisible(false)` on it)

And of course, I didn't mean to propose _"change just for the change"_. I just remember your (very valid) request to make small changes. I meant this change as a ground for some other enhancements (IMO useful). But this strict binding of this menu with tabs visibility closes some doors...

**Comment by mvidelgauz** [comment]
@githubuser0xFFFF After re-reading your message I think I now better understand what you mean... Seems that TabsMenu button was initially designed _just_ for the case when tabs are not completely visible, and it is only my understanding that it can be used as an independent widgets list...

I now feel that both understandings may be valid and it is now up to you if you wish to extend the list of usage scenarios for this button or not...

I just wanted to express my opinion that tabs are not the only possible way for switching, so another means for this operation _might_ be useful...

**Comment by githubuser0xFFFF** [comment]
@mvidelgauz Yes, you are right, that was my intention:

> TabsMenu button was initially designed just for the case when tabs are not completely visible, and it is only my understanding that it can be used as an independent widgets list...

For me, the tabs are the view for the model (the list of dock widgets) and the tabs in turn are the model for the tabs menu button.

But I can also understand and follow your model view idea and I will not block this request, if I can see the bigger picture. So I would like to ask you to cleanup this pull request (remove the hidden tabs stuff from the demo).

Btw. the Qt Advanced Docking System is now in the Qt marketplace.

**Comment by mvidelgauz** [comment]
Thank you @githubuser0xFFFF 
I reverted MainWindow to the sate on your master (except one empty line just for better grouping of different dock widgets creation code parts)

For you to see a bigger picture I will need to eighter implement some of my other ideas with code based on these changes (or draw a scetch, where I am not very proficient...), or try to just explain in words... I'll try to do it in the next few days.

But I think these changes do not harm your implementation, nor do they introduce code complication. Otherwise, even if you will accept my other ideas these changes will have to be re-implemented anyway...

**Comment by githubuser0xFFFF** [comment]
Hi, i will close this for now, because it will not go into master.

**Pull request closed without merging**
