### PR TITLE
Add hover effect for drop indicators

### PR DESCRIPTION
**Pull request by farmovit**
Improved mental perception by adding hover effect to drop indicators.

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
I just tested it. It is a nice idea - i like it. The hover effect is noticeable but quite subtle - maybe too subtle. But that can be improved later. One thing that I would like to see now, is that the hover effect is a configuration option. So please add a dock manger configuration flag for this effect so that users that may don't like it, can turn it on and off.

Thank you for your contribution.

**Comment by farmovit** [comment]
Ok. Thank you.

Should the flag be disabled by default?

**Comment by farmovit** [comment]
I added config flag and enabled it by default.

**Comment by githubuser0xFFFF** [comment]
Thank you, I will look into it tomorrow

**Comment by githubuser0xFFFF** [comment]
Hi @farmovit,

now I had some time for a closer look at your solution and I'm not completely happy with it. The code for the hover effect is spread across several places and functions but `QWidget` already has built-in support for [hover events](https://doc.qt.io/qt-5/qhoverevent.html). The drop indicator icons are widgets - they are implemented as `QLabel` with a pixmap. 

So I think, the better solution would be, to provide drop indicator widgets with proper hover support. That means, I would implement a `CDropIndicatorWidget` class that supports hovering out of the box. To keep it simple, you could derive from `QLabel`. Then you can add a new function `setIndicatorPixmap` where you can set the pixmap for different modes (normal and hover). Then you need to handle the `QEvent::HoverEnter` and `QEvent::HoverLeave` events properly and simply call `QLabel::setPixmap` to assign the right pixmap

With this solution you have all the hover code in one place and you do not need to modify other files. That means, instead of creating a `QLabel` as a drop indicator widget, you create a `CDropIndicatorWidget` instance.

**Comment by farmovit** [comment]
Ok, thank you.

I will rework it soon.

**Comment by farmovit** [comment]
Hi @githubuser0xFFFF,

I am trying to implement `CDropIndicatorWidget` and I am facing with a problem. I am getting no hover events in my `CDropIndicatorWidget`. You can find in the code that I reimplemented `virtual bool event(QEvent* event)` function and I printed logs for some events there. But no prints were occurred. Do you maybe have some ideas why is this happen?

Also I am wondering, how do you ok with this realization of `CDropIndicatorWidget`?

**Comment by githubuser0xFFFF** [comment]
Ok, I just tested it here and the reason that you do not get any events is, that the mouse has been pressed on another widget - that means the other widget has grabbed the mouse and the `CDropIndicatorWidgets` will not receive any events. So my idea of using the hover functionality was wrong and does not work :o(

Regarding your implementation: Try to keep `CDropIndicatorWidget` as simple as possible. Just add the functions to set a normal and a hovered image - no references to other dock widget classes. Then add a function to set the hovered state:

`void setHovered(bool Value);`

Then add another function:

'void updateHoverState()`

This function needs to get the global mouse cursor position and map it into its own coordinates. Then you can check, if the mouse is inside of the widget geometry. Depending on the mouse position, you can call setHoovered() with true or false.

Now you only need a function that triggers `updateHoverState()`. You can do this in the `CDockOverlay::showOverlay` function. This function is called whenever a floating window or floating drag preview is moved around. You can then iterate over the drop indicators and call the `updateHoverState()` function.

This is not as nice as the built in hover support but it comes wuite close.

**Comment by farmovit** [comment]
Thank you for your reply and comments. I will keep trying to implement this.

There is just one thing I want to discuss.

> no references to other dock widget classes

The reason, why `CDropIndicatorWidget` depends on `DockOverlayCrossPrivate` is colors. We need colors to create pixmap, but these colors is configured by `CDockOverlayCross` and I don't want to duplicate this functionality in the `CDropIndicatorWidget`. What is the best solution to manage this in your opinion?

**Comment by githubuser0xFFFF** [comment]
At the moment, the pixmap is created by the `CDockOverlayCross` so your `CDropIndicatorWidget` does not need any colors. I just gets the ready images:

```c++
QWidget* createDropIndicatorWidget(DockWidgetArea DockWidgetArea,
		CDockOverlay::eMode Mode)
{
  QDropIndicatorWidget* l = new CDropIndicatorWidget();

  l->setIndicatorPixmap(createHighDpiDropIndicatorPixmap(size, DockWidgetArea, Mode), QIcon::Normal);
  l->setIndicatorPixmap(createHighDpiDropIndicatorPixmap(size, DockWidgetArea, Mode), QIcon::Active);
}
```

If you want to move the whole painting code into CDropIndicatorWidget, you can do this but it is a lot more work and I would prefer a less complex pull request or you need to do these chanegs in several steps.

**Comment by farmovit** [comment]
I got your point. Thank you.

**Comment by farmovit** [comment]
Hi @githubuser0xFFFF,

I was thinking about your propagation and I got that not the all functional will work as expected if we make dependency on mouse cursor position. I tried to show, what will not work on the attached GIF.

As you can see, the hover effect works (and should work I suppose) not only when we are inside of a drop indicator, but also when we are at the tab of a widget. IMHO, If that behavior does not work, we will have not the full picture of what is going on.

hover

**Comment by githubuser0xFFFF** [comment]
Then you could do the following. The function `dropAreaUnderCursor` is also called  when the mouse drags the floating widget. This function already iterates over all drop areas and identifies the drop area and also considers the case when the mouse cursor is over the title bar.

So instead of using the 'showOverlay` function you use the `dropAreaUnderCursor` function. You modify this function that is udpates the hover state of the previous hovered drop indicator widget and that it updates the the hover state of the  new hovered drop indicator widget.

**Comment by farmovit** [comment]
@githubuser0xFFFF 

To be honest, I don't like it because in fact we then get side effect in getter function that is marked as `const`.

> that is udpates the hover state of the previous hovered drop indicator widget and that it updates the hover state of the new hovered drop indicator widget.

You can see my first commit where I implemented it, but it was not inside getter.

**Comment by githubuser0xFFFF** [comment]
I have thought so much about the implementation already that I think I will implement the feature quickly in the next few days if this is o.k. for you.

**Comment by farmovit** [comment]
Yes, it is ok. A bit annoyingly, but anyway I would glad to see this future :)

As for continuation of this future I would like to see some DropIndicatorFactory/Provider that allows users to provide their own drop indicator widgets. For example, I currently want to use images as drop indicators but I can't do it. Would you mind if I create that issue as an enhancement?

**Comment by githubuser0xFFFF** [comment]
> Yes, it is ok. A bit annoyingly, but anyway I would glad to see this future :)

Yes I understand. If you say, you would like to implement this, then it is o.k. You are almost there. The idea with the `dropAreaUnderCursor` function was more to give you a direction. 

> To be honest, I don't like it because in fact we then get side effect in getter function that is marked as const

That is completely right and I agree. But then it is up to you, to provide a better way. The nice thing about this function is, that it already does the iteration for you. So there are several ways you could go. For example, you could provide an extra DockOverlay function `updateDropIndicators`. Then the dragging code in the floating widget calls `dropAreaUnderCursor` and then uses the returned value, to call `updateDropIndicator`. Another option would be that the function `updateDropIndicators` internally calls `dropAreaUnderCursor` and then returns the drop area. The dragging code then simply calls  `updateDropIndicators` instead of `dropAreaUnderCursor`.

So if you would like to implement it, then you can do it.

**Comment by farmovit** [comment]
Ok. Then I will try.

**Comment by farmovit** [comment]
Hi @githubuser0xFFFF,

I tried to make function `DockOverlay::updateDropIndicators` and replace to it `DockOverlay::dropAreaUnderCursor`. But I faced a lot of issues during this work, because the are a lot places where `DockOverlay::dropAreaUnderCursor` is calling, and, moreover, there is `DockOverlay::visibleDropAreaUnderCursor`. So it turns that it is not so easy for me to implement it in the way you want because I need a lot of time to figure out how all this logic works and what issues should I consider to make it work. So, I think it would be better if you implemented it.

Sorry and thank you for your time!

**Comment by githubuser0xFFFF** [comment]
Ok, thank you for your work. I will try to implement your proposal

**Pull request closed without merging**
