### PR TITLE
Added DockAreaHideDisabledButtons configuration flag

### PR DESCRIPTION
**Pull request by mvidelgauz**
When this flag is set disabled dock area buttons will not appear on the tollbar at all (enabling them will bring them back)

(This serves not just "CentalWidget" purpose but to me seems to be a generally possible user preference)

### CODE REVIEW

**Comment by mvidelgauz** [comment]
@githubuser0xFFFF Sorry, I think I found one improvement Please hold with this PR, I am going to push updates to my branch

**Comment by mvidelgauz** [comment]
@githubuser0xFFFF I have a question for you regarding "testConfigFlag" function in "DockAreaTitleBarPrivate". It is a non-static method, which from a design point of view may seem like configurations might be overridden per DockAreaTitleBar instance. But currently, it's implementation just deals with global CDockManager::configFlags(). 
Did you mean to just have "syntax sugar" with this function in DockAreaTitleBarPrivate or you really plan to have configurations overridden in the future?
In first case, I can use CDockManager::configFlags() also for CTitleBarButton instance initialization. In the second case, I should either pass one more parameter to CTitleBarButton's ctor (like it is now) or provide  CTitleBarButton with backreference to DockAreaTitleBar[Private] (to simplify future enhancements)

The same question is about testConfigFlag() in DockWidgetTabPrivate.

**Comment by githubuser0xFFFF** [comment]
The function is only syntactic shugar and I thing it can be made static.

**Comment by mvidelgauz** [comment]
Thank you @githubuser0xFFFF. So, for now, I will just make it static and use it in CTitleBarButton's ctor.
(Although IMO for future product evolvement it makes sense to have per DockAreaTitle configuration overriding)

**Comment by mvidelgauz** [comment]
@githubuser0xFFFF  Ok, I pushed updates to the branch, could you please review the PR now?

**Comment by githubuser0xFFFF** [comment]
Thank you, I will review your pull request within the next days.

**Comment by githubuser0xFFFF** [comment]
Thank you for your pull request, I just merged your changes

**Pull request merged**
