### PR TITLE
upgrade PyQt build

### PR DESCRIPTION
**Pull request by luelista**
Hi,
I'm working on upgrading the build process of the PyQt bindings to the current recommendations of the PyQt-builder / sip authors, so that it works with the current version of sip and pip.

It's currently WIP because I can't build the resources file (ads.qrc) reliably yet. It only works if the build directory is in a subfolder of the main repo, because I had to hardcode the path in the config file (`qmake-settings = ["RESOURCES += ../../src/ads.qrc"]`. 

Once I found out the right way to solve this I'll update this PR. I thought I'd still open this already, if you have any feedback regarding this update.

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Thank you for your contribution. I cannot help you much, because I have not experience yet with PyQt. Just tell me when you think the pull request is ready and I will merge it.

**Comment by luelista** [comment]
I fixed the build problem, no hardcoded path any more :) I'm going to test this on some more platforms, and tell you once it's ready.

**Comment by githubuser0xFFFF** [comment]
This sounds great. Thank you very much for your help.

**Comment by Zholtikov** [comment]
@luelista  Do I understand correctly that when you're done - there will be a PyPi package that can be installed with modern versions of pyqt-sip and pyqt ? 
Can you tell me when you plan to finish? I really look forward to these changes...

**Comment by githubuser0xFFFF** [comment]
Thank you very much for this great contribution,

**Comment by Zholtikov** [comment]
@luelista 

Installing via pip and via whl(windows) really works. 
But `from PyQtAds import QtAds` says `cannot import name 'QtAds' from 'PyQtAds'`

**Pull request merged**
