### PR TITLE
Add dock order preference

### PR DESCRIPTION
**Pull request by SyarifFakhri**
Hi @githubuser0xFFFF, hope you are having a good day 😄. This is a PR to add an optional auto hide dock order preference to some dock widgets. Reason for this addition is that some users prefer to pin and unpin docks liberally, and when this occurs the tab order tends to shift around. This means that the UI gets inconsistent pretty quickly (e.g. if they unpin a dock that was previously at the first position, and they re-pin it, it'll be at the last position instead). This addition let's the programmer set a fixed order so that the auto hide UI can always be consistent for the end user.

See the following example:
insert_tab_with_dock_order

(table 2 is always inserted after table 1 and before table 5 etc.).

I've also added some documentation:

> Optionally, you may set the auto hide tab order preference, set via `DockWidget->setAutoHideTabOrder(n)`. You must set it to a positive float value (negative float values are ignored). The default value is -1.0 and will be ignored. Setting it to a lower positive float value will order tabs behind docks that have higher float values. For example, if `Dock Widget A` is set to 1.0 and `Dock Widget B` is set to 2.0, `Dock Widget A` will always be inserted behind `Dock Widget B` in the auto hide sidebar.

> If some dock widgets have an order but others do not, the widgets without an order set will be skipped. If none of the dock widgets have a set order, then the dock widget with an order set will be set at the end (the default behavior).

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Hi @SyarifFakhri, first I would like to thank you for your pull request - it is an interesting feature. It is always interesting to see, which requirements some users have. Something that I really would like to know is the reason someone pins and repins a over and over again.

From my personal experience of using our software, I normally work with windows pinned or unpinned. Normally I do not pin and unpin the windows very seldom. So maybe you could give me an idea, why the users of your software pin and unpin their dock widgets that often. I would like to understand the requirements of the users for this pull request.

Do you also take the order into account when loading perspectives?

Thank you.

**Comment by githubuser0xFFFF** [comment]
Ok, that sounds quite interesting. 

But the idea of the pinned dock widgets is, that you can show and hide them quickly, without wasting space in your user interface. That is the big advantage of pinned autohide dock widgets. 

If you pin and unpin it all the time, then it feels like someone misuses the autohide functionality. If you pin and unpin dock widgets, then you do not need a auto hide widget but a normal dock widget that you can show and hide or a floating widget. The autohide functionality is not meant for toggling visiblity of dock widgets in my opinionn

So instead of toggling a docked widget between visible and hidden, they use the autohide tabs to pin and unpin them - this feels like a misuse of the autohide concept for me.

If they have different "modes", then the perspectives is the perfect thing because you can quickly switch between completely different window configurations. So at the moment I'm not completely convinced from the given use case.

**Comment by SyarifFakhri** [comment]
I totally understand where you're coming from. Actually I agree that this is a use case for perspectives. However switching between perspectives can sometimes be tedious for a user, when they just want to temporarily unpin and repin a dock, it's very intuitive and quick to hit the pin/unpin button. Anyway, I understand this increases the complexity of the codebase, so it is totally up to your prerogative 🙂

**Comment by nickdademo** [comment]
@githubuser0xFFFF I also think it would be great to have this (at least as a configurable option) as I have personally seen many customers struggle with unexpectedly re-arranged sidebar tabs.

**Comment by githubuser0xFFFF** [comment]
@nickdademo When will be sidebar tabs re-arranged unexpectedly?

**Comment by nickdademo** [comment]
> @nickdademo When will be sidebar tabs re-arranged unexpectedly?

During unpinning and pinning the docks.

**Comment by githubuser0xFFFF** [comment]
@nickdademo Is just tested this in the demo an could not reproduce this. If I add a sidebar tab then it will always be added to the end of the tabbar and the tabs will not be re-arranged unexpectedly. Also if I remove a tab I do not se any unexpected re-arrangement of the tab order.

**Comment by SyarifFakhri** [comment]
@githubuser0xFFFF I think it depends on what you consider unexpected. The following case of unpinning from the middle tab and then re-pinning at the end is unexpected for some people, as the tab started in the center, but has 'jumped' to the end after re-pinning:

tabs_rearranging

**Comment by githubuser0xFFFF** [comment]
I which use case do you unpin and pin a dock widget again?

**Comment by SyarifFakhri** [comment]
> But if your merge request is implemented and I have 3 tabs in the sidebar, and then pin another DockWidget with a priority between the first and second tab, then I would consider this unexpected because nobody knows all the priorities and the tabs 2 and 3 would jump unexpectedly 1 tab to the right. So if you rely on a certain tab to be on a certain place, then you will be surprised that the tabs will be re-arranged unexpectedly, if you pin a tab with a priority that is not the lowest and not the highest. That is really unexpected.

I'm not really sure what you mean here, but for some users what's expected for them is that what they see from the beginning (the first time they use the application) stays the same whenever they use the application, no matter how they unpin and pin. I think what you are saying is true for some users as well, this is why I would like to add it as an optional config 😃.

> In which use case do you unpin and pin a dock widget again? Maybe you can show a screenshot from your application that shows why users pin and unpin auto-hide widgets. At the moment, I'm not convinced.

Absolutely! Here's a video showing what is a common use case for a customer:

[dock_view_pin_unpin.webm](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/4475295/0e246d55-a7e2-4195-8269-bf8f3aa2b5a0)

In that case, they are dragging around a `graphicsitem` on the `qgraphicsscene`. The dock corresponding to the `qgraphicsitem` starts pinned at the 6th position. In this case, the user has typically made the association that the `qgraphicsitem` dock is at the 6th position. The dock is unpinned so that the user can see live updates as they are dragging around the `qgraphicsitem`. When the user is done, they pin it back again. When they want to see it again, they try to go back to the 6th position, but that is incorrect, because they have repinned it, so it is actually the last position. Now when they open the 6th position they end up confused.

> If they have different "modes", then the perspectives is the perfect thing because you can quickly switch between completely different window configurations. So at the moment I'm not completely convinced from the given use case.

Unfortunately, it's difficult to use perspectives in this case, because the `qgraphicsitem` is dynamically created. In fact, there are a few different types of such `qgraphicsitems` and they may come in any number and combination. Due to the fact that the user typically wants to see live updates on some items and sometimes wants to see the whole image, it leads to this situation where they are pinning and unpinning. Of course this is not the only use case, but the general idea is the same, they may want to see live updates temporarily while working in a separate dock, so they unpin, and when they pin it back, it has become unexpectedly rearranged.

Hope this is understandable, thank you for your consideration 😃

**Comment by githubuser0xFFFF** [comment]
@SyarifFakhri Hi, is this pull request still relevant? Because it does not play well with the drag and drop to auto hide because dragging a DockWidget to auto hide sidebar oder dragging an auto hide tab will ignore the auto hide dock order preference.

Do you want to update your pull request or can I close it?

**Comment by SyarifFakhri** [comment]
Hi, please feel free to close it.

**Pull request closed without merging**
