### PR TITLE
Central Widget concept added

### PR DESCRIPTION
**Pull request by hulswit**
Added option to set a CENTRAL WIDGET into the Dock Manager. It is an important part of a docking system. If a central widget is set, it will be the only widget that will be stretched with the container (window) as the remaining dock widgets will only be resized on vertical direction if docked left or right and in horizontal direction if docked top or bottom. This is a standard behavior of all docking systems where an central widget is introduced.
Also this update enabled a DockWidget to be user resizable in defined direction only. if a DockWidget is set to be user resizable only horizontally and is docked at bottom area, the splitter hosting this dock widget  will have the handle bordering this dock widget disabled.
Third update is the option to set a dock widget to have no title bar. If a dock widget is set to have no title bar and is the only widget in a dock area, the area title bar will be hidden.

### CODE REVIEW

**Comment by SleepProgger** [comment]
+1 for making it easier to have a central widget.

Hiding the titlebar when only one widget is in that area was merged with #227 though, albeit your function name is likely better.

**Comment by githubuser0xFFFF** [comment]
Thank you for your pull request and your work but I do not feel comfortable with merging the request and I have to admit, that I do not understand it completely. Here are the things I'm not happy with:

- the pull request is quite big, changes a lot of files and adds a number of functions / features which makes it hard for me to understand and properly review it. It also changes a lot of things which increases the risk of potential errors - I already found some strange things in the central widget demo
- with the current state of the library it is already possible to implement a central widget. You just need to create a dock widget that is not floatable, movable and closable and create a dock area without a title bar. Then you have a central widget that the user cannot delete or move. So I do not fully understand the improvement of your central widget concept.
- your change adds runtime overhead because the `updateSplitterHandles()` function is called on many places. I do not really like the idea of adding runtime overhead for a feature that has been requested by one single user so far. So I'm not convinced that this change really adds value for many other users
- I'm not happy with the idea / concept of limiting the resizing direction of dock widgets. The idea and concept of the docking system is, to give the user a great flexibility in placing and arranging windows with different functionality. This concept only works well, if the widgets are resizable. 
- the functionality of a dock area without a title bar has been implemented recently

So I have to say sorry, because I know that your have put a lot of work into this change, but I'm not going to merge it. If you would like to implement these changes, you need to maintain and implement this in your own fork.

**Comment by hulswit** [comment]
The concept of central widget as you can see it in other docking frameworks is that the central widget is the only one to stretch with the main window. Take Visual Studio as example. If you dock the Solution Explorer (or Toolbox...) on left or right side, it will not resize horizontally, only vertically when you resize the main window. And this is in my opinion important part of central widget concept. The additional option to have fixed size (non user resizable) dock widgets is not a must have, but I think a nice to have feature. I am now working on moving an existing application from MFC/ToolkitPro into Qt and this feature is a requirement. The scenario is that there is a dock widget that contains timeline widget with fixed height. it is not movable, but the user can still dock other dock widgets above or below it. The timeline however needs to be of fixed height and thus the Splitter shall have the bordering handles disabled. 
I understand that my pull request is big. So maybe it makes sense to close it and split into individual requests if you find my argument relevant.

**Comment by githubuser0xFFFF** [comment]
Ok, I just checked Visual Studio and was able to reproduce the described behaviour. I mainly work with Eclipse, which is also a code editor with docking support and which I have taken as a template for my implementation. Unlike Visual Studio, scaling the application window scales all dock widgets as well, not just the central code editor. So I wouldn't say that such a concept of a central widget is mandatory, but just a certain way of implementing the docking. Eclipse works well and I have no issues with the way docking works. Which of the two concepts is better? I have no clue.

But anyway, I understand your point and I also understand that all people that know Visual Studio take this as the blueprint for their implementation and would like to have the same behaviour. So I think I would accept the concept of a central widget. 

So how are you going to implement this? If you create a small pull request with only this feature, I'm willing to review and accept it.

**Comment by hulswit** [comment]
OK. I will create a new pull request with the central widget concept.

**Comment by SleepProgger** [comment]
Just as little heads up: You can also currently have multiple DockContainer which can lead to something like a Central Widget.
(The lib isn't designed for this i think but it works fine.)
image

That being said more intuitive central panel concepts would be nice for sure.

**Pull request closed without merging**
