### PR TITLE
setAllowedAreas for individual DockAreaWidget

### PR DESCRIPTION
**Pull request by mvidelgauz**
Following issue https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/104
This change allows setting DockAreas per individual DockAreaWidget. By default, all areas are allowed to maintain backward compatibility.

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Hi, in your pull request you forgot, that tabbing is not only possible via the center dock area but also via moving a dock widget over the title bar of a dock aera. I will merge your pull request and fixt his afterwards.

Thank you for your contribution.

**Comment by mvidelgauz** [comment]
Hi,
thank you for pointing out my mistake!
As you probably guess, my final goal is to emulate CentalWidget. To achieve this, besides hiding those three buttons, I also do 
`DockWidget->tabWidget()->setVisible(false);`
That's why I didn't catch this mistake in my tests :)

Btw, I am now trying to go further and implement a possibility to hide those three buttons only for a given dock widget rather than disabling them globally (I want to leave this nice feature for other docks).
I see several approaches, and I will appreciate it if you could discuss them with me (kind of "design" review) before I will code mods that you will later won't accept :)
Would you be open to such a "design review"?

**Comment by githubuser0xFFFF** [comment]
But if you need a cetral widget, why don't you stay with the standard Qt docking system?

**Comment by mvidelgauz** [comment]
Because this one is much better than that standard in many aspects :)
- Drop overlays
- Many customizations
- Additional features (and being actively developed)
...
My application is going to have a lot of widgets that I want to be controlled by this system, with the only single exception of one area which is conceptually different from the app philosophy point of view :)

**Pull request merged**
