### PR TITLE
Fix memory leak in CDockContainerWidget::restoreState

### PR DESCRIPTION
**Pull request by gafusss**
delete old root splitter layout item

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Thank you

**Comment by iam-peter** [comment]
There is also a potential memory leak here?
DockContainerWidget.cpp:592
```
	if (!TargetAreaSplitter)
	{
		QSplitter* Splitter = newSplitter(InsertParam.orientation());
		Layout->replaceWidget(TargetArea, Splitter);
		Splitter->addWidget(TargetArea);
        updateSplitterHandles(Splitter);
        TargetAreaSplitter = Splitter;
	}
```

**Comment by githubuser0xFFFF** [comment]
@iam-peter You might be right. The code looks similar to the fixed one. @gafusss What do you think?

**Comment by gafusss** [comment]
> @iam-peter You might be right. The code looks similar to the fixed one. @gafusss What do you think?

Looks like it, but I can't figure out how to reproduce it to test

**Pull request merged**
