### PR TITLE
Add dockindock example

### PR DESCRIPTION
**Pull request by jporcher**
Added example illustrating how issue https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/306 can be adressed by specializing DockManager class.

Note, I had to manualy delete children to prevent a crash. This is likelly related to https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/307

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
Thank you for the merge request. Please check why the tarvis CI build failed:

https://travis-ci.org/github/githubuser0xFFFF/Qt-Advanced-Docking-System/jobs/766219293

**Comment by jporcher** [comment]
Fixed missing include required for Linux. Sorry about that.

**Comment by jporcher** [comment]
Now I just tested addPerspective/openPerspective....and unfortunately this does not work. After opening a perspective, the tabs "Inner 1", "Inner 2" and "Inner 3" under the "Group" tab are all gone.

I tried to see how to fix it, but looks like it cannot be done from the proposed DockManagerWithInnerTabs class, ads classes themselves shall be modified (or at least some functions shall be made virtual to let DockManagerWithInnerTabs  override them to modify the default behaviour) and I did not manage to make it work. As far as I could debug, the Inner tab states are apparently saved into the perspective state, but, during the open operation, at some point the "Group" CDockContainerWidget object is gone and so the Inner tabs does not get restored.

**So I believe:**
- If you accept this pull request, we may mention in a comment that perspectives do not work anymore?
- Or, I can commit the changes I added to the example to add menus to save/load perspective and play with them and then maybe someone can have a look at what's wrong and make openPerspective work?
- Or, you may simply reject the Pull request if you consider supporting perspectives is a must so example not supporting them cannot be published!

**Comment by jporcher** [comment]
Actually, maybe the approach is wrong, I'm using CDockContainerWidget for groups, maybe I should use a CDockManager directly. Then I could recursivelly call addPerspective/openPerspective from the top dock manager to the children. This would allow to have a depth of more than 1 and is likelly to make save/restore perspective work better. You may want to put this pull request on hold and I'll try to work on this different approach next week (still isolated in an example) and see if it's better or not.

**Comment by jporcher** [comment]
Just pushed a new example. It's more complex but works pretty well (even when saving/restoring perspectives)!

**Comment by githubuser0xFFFF** [comment]
Thank you, I just merged this. On which systems did you test this (Windows, Linux, Mac).

**Comment by jporcher** [comment]
Thanks. I tested Windows only.

**Comment by githubuser0xFFFF** [comment]
Hi,

I just tested your dockindock example - really nice. If I close the example, I see the following error in the console:

```
pure virtual method called
terminate called without an active exception
```

Could you please have a look into this issue and fix it? 

Thank you.

**Comment by jporcher** [comment]
Done: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/pull/317

Sorry about that.

**Comment by githubuser0xFFFF** [comment]
@jporcher  Hi, A user just reported a crash in the dockindock example (#585). I think the problem is related to the example and not the ADS library. Because the example shows functionality that is not part of ADS I think the best option would be to remove it.

Please tell me, if you would like to fix the issue or if I should remove the example.

**Comment by jporcher** [comment]
Hello,
I don't have access to Ubuntu machine, but I could reproduce under Windows. It's not specific to the example, it's due to the code I added to fix the memory leaks. I'll investigate and try to fix this.

**Comment by jporcher** [comment]
I could reproduce the crash under Windows

**Comment by jporcher** [comment]
My mistake, the problem comes from the example itself, not from the bugfix. I'll try to see if I can fix the example.

**Pull request merged**
