### PR TITLE
Account for removed widgets when closing other tabs

### PR DESCRIPTION
**Pull request by Tectu**
If the application code removes a widgets when it gets hidden, it will no longer be in the layout, and thus the index needs to be updated to not skip any tabs.

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
The latest commit added the new DockWidget flag `DockWidgetDeleteOnClose`. This deletes the dock widget if the user closes a DockWidget or if the user closes a floating widget that contains only one single DockWidget.

So normally there should be no need for the application to remove a widget. Please check, if this pull request is still valid after the latest changes.

**Comment by XenotriX** [comment]
I'll look into it but at a glance it seem that this doesn't allow the application to prevent a dock from closing, which is something we need in our application.

**Comment by XenotriX** [comment]
I quickly tested it and it looks like the issue described here is still a problem even when using `DockWidgetDeleteOnClose`. If you create a few Editors in the demo application, move them all into a single area and try the `Close Others` button you'll see that it's won't remove all of them.

**Comment by githubuser0xFFFF** [comment]
I just commited a change that properly fixes the index in case a dock widget has the DeleteOnClose feature flag set

**Comment by Tectu** [comment]
It would be nice if you could link the commit in here so we can find it more easily when we get to checking it out :)

**Comment by githubuser0xFFFF** [comment]
It ist the commit a45a035 - the change ist at the same location like your proposed change.

**Pull request closed without merging**
