### PR TITLE
Remove setup.py and related files

### PR DESCRIPTION
**Pull request by n-elie**
setup.py, setup.cfg and versioneer.py does not seems to be useful anymore since the move to pyqt-builder

### CODE REVIEW

**Comment by githubuser0xFFFF** [comment]
@n-elie Your last merge request killed the CI workflows linux-builds. Please check if you can fix this. If you do not have a quick solution, I would revert the changes for the moment.

**Comment by n-elie** [comment]
Sorry for that. I assume you are refering to #489 and not this one?
The linux build fail at Qt installation, so this does not seem related to my changes.
However, if the linux build uses ads.pro, this might cause problems as linking flags should be adapted to Qt versions used. `-lqtadvanceddocking` has to be replaced by `-lqt6advanceddocking` or `-lqt5advanceddocking`

**Comment by githubuser0xFFFF** [comment]
@n-elie Ahh, yes I see. Sorry, it seems to be a problem in the Qt installation GitHub action - sorry.

**Comment by n-elie** [comment]
May be related to this: https://github.com/jurplel/install-qt-action/issues/130
Upgrading `jurplel/install-qt-action` to v3 might help

**Comment by githubuser0xFFFF** [comment]
@n-elie Thank you for this hint. I initially tried v3 but switched to v2 because of errors. I will try again.

**Pull request merged**
